# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.dotfiles/oh-my-zsh

ZSH_CUSTOM=$HOME/.dotfiles/zsh-custom
ZSH_THEME="my-candy"

#CASE_SENSITIVE="true"

# DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

HIST_STAMPS="yyyy-mm-dd"


plugins=(archlinux systemd firewalld screen \
         git \
         ruby rvm gem rake bundler \
         docker docker-compose docker-machine \
         kubectl helm \
         httpie nmap \
         rust cargo \
         ant mvn sbt scala \
         colored-man cp \
         customize)

source $ZSH/oh-my-zsh.sh


export EDITOR=vim
export SUDO_EDITOR=rvim

export LANG=en_US.UTF-8
export TERM=xterm-256color

export PATH=$HOME/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH

# vim: sw=2:ts=2:et:

